/**
 * Created by akireyeu on 24.12.2019.
 */

public with sharing class ArtTaskProductTableApex {
//    @AuraEnabled
//    public static List<Review__c> getReview(String id)
//    {
//        return [SELECT Id, Description__c, Views__c, Like__c, Dislike__c FROM Review__c  WHERE Product__r.Id=:id];
//    }
//    @AuraEnabled
//    public static void setLike(String id)
//    {
//        Review__c r = [SELECT Id, Views__c, Like__c, Dislike__c FROM Review__c  WHERE Review__c.Id=:id];
//        r.Like__c++;
//        update r;
//    }
//    @AuraEnabled
//    public static void setDislike(String id)
//    {
//        Review__c r = [SELECT Id, Views__c, Like__c, Dislike__c FROM Review__c  WHERE Review__c.Id=:id];
//        r.Dislike__c++;
//        update r;
//    }
}